EPOCHS: 10
BATCH_SIZE: 2
LEARNING_RATE: 0.001
WEIGHT_DECAY: 0.01
DROPOUT_RATE : 0.3



# EPOCHS: 5-10               # Range from trial.suggest_int('epochs', 5, 10)
# LEARNING_RATE: 1e-5-1e-3   # Range from trial.suggest_float('lr', 1e-5, 1e-3, log=True)
# BATCH_SIZE: [16, 32, 64, 128]  # Options from trial.suggest_categorical('batch_size', [16, 32, 64, 128])
# WEIGHT_DECAY: 1e-5-1e-1    # Range from trial.suggest_float('weight_decay', 1e-5, 1e-1, log=True)
# DROPOUT_RATE: 0.1-0.5      # Range from trial.suggest_float('dropout_rate', 0.1, 0.5, step=0.1)
# OPTIMIZER_NAME: ['Adam', 'SGD', 'RMSprop']  # Options from trial.suggest_categorical('Optimizer_name', ['Adam', 'SGD', 'RMSprop'])